export {
  Add01Icon as PlusIcon,
  Archive01Icon as ArchiveIcon,
  ArrowLeft01Icon as ArrowLeftIcon,
  ArrowUp01Icon as ArrowUpIcon,
  ArrowUpRight01Icon as ArrowUpRightIcon,
  BalanceScaleIcon as ScaleIcon,
  BarChartIcon as BarChart2Icon,
  Bell,
  BookOpen01Icon as BookOpenIcon,
  Braces,
  Briefcase01Icon as BriefcaseIcon,
  Cancel01Icon as XIcon,
  ChartIcon as ChartIcon,
  CheckCircle,
  Checkmark as CheckIcon,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  CircleDot as CircleIcon,
  Command,
  Copy01Icon as CopyIcon,
  CreditCard,
  Crown,
  Download01Icon as DownloadIcon,
  Edit01Icon as PenLineIcon,
  ExternalLink,
  Eye,
  EyeOff,
  Feather,
  FileText,
  FilterIcon,
  FlaskConical,
  Folder01Icon as FolderIcon,
  FolderOpen,
  FolderPlus,
  Gem,
  Globe,
  Hand,
  HandHeart,
  Handshake,
  Image01Icon as ImageIcon,
  Inbox,
  InformationCircleIcon as InfoIcon,
  JusticeScale01Icon as ScalesIcon,
  LayoutDashboard,
  LayoutPanelLeft,
  LayoutTemplate,
  Library,
  LifeBuoy,
  Lightbulb,
  Lightning,
  Link01Icon as LinkIcon,
  Loading03Icon as LoaderIcon,
  Lock,
  Lock as LockIcon,
  Logout01Icon as LogOutIcon,
  Mail01Icon as MailIcon,
  MessageCircle,
  Mic,
  MicOff,
  Minus as MinusIcon,
  Moon,
  MoonStar,
  MoreHorizontal,
  PanelLeft,
  PenLine,
  Phone as PhoneIcon,
  PhoneCall,
  PhoneForwarded,
  PhoneOff,
  Play,
  Pause,
  Plug01Icon as PlugIcon,
  Radio,
  Refresh as RefreshCwIcon,
  Rocket01Icon as RocketIcon,
  RotateCcw,
  Search01Icon as SearchIcon,
  SentIcon as SendIcon,
  Settings01Icon as SettingsIcon,
  Share01Icon as Share2Icon,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Sparkle,
  Sparkles,
  Sun,
  Target,
  Text as TypeIcon,
  Tick02Icon as TickIcon,
  Trash2 as Trash2Icon,
  TrendingUp,
  Unlink01Icon as UnplugIcon,
  Upload01Icon as UploadIcon,
  UserIcon,
  Volume2,
  WavingHand01Icon as HandWavingIcon,
  Workflow,
  Zap,
} from "@hugeicons/core-free-icons";

export { Heart as HeartStraightIcon } from "@hugeicons/core-free-icons";
