#!/usr/bin/env bash
# Idempotent repository bootstrap for the Anselio Cloud Agent environment.
# Prepares a local Postgres (with pgvector), Node dependencies, and the DB schema.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PG_VERSION=16
DB_NAME=anselio
DB_USER=anselio
DB_PASS=anselio

echo "==> [1/6] Ensuring Postgres $PG_VERSION + pgvector are installed"
if ! dpkg -s "postgresql-$PG_VERSION" >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    postgresql postgresql-contrib "postgresql-$PG_VERSION-pgvector"
fi

echo "==> [2/6] Starting Postgres cluster"
sudo pg_ctlcluster "$PG_VERSION" main start 2>/dev/null || true
for _ in $(seq 1 30); do
  if pg_isready -h 127.0.0.1 -q; then break; fi
  sleep 1
done
pg_isready -h 127.0.0.1 -q

echo "==> [3/6] Ensuring role, database and pgvector extension exist"
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASS' SUPERUSER;"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1 || \
  sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"
PGPASSWORD="$DB_PASS" psql -h 127.0.0.1 -U "$DB_USER" -d "$DB_NAME" \
  -c "CREATE EXTENSION IF NOT EXISTS vector;" >/dev/null

echo "==> [4/6] Ensuring local .env / .env.local exist (gitignored, no real secrets)"
LOCAL_DB_URL="postgresql://$DB_USER:$DB_PASS@127.0.0.1:5432/$DB_NAME?schema=public"

# .env — full template copied from .env.example with local dev values filled in.
# The custom server (server/index.ts) loads this via `import "dotenv/config"`.
# Third-party integrations (Twilio, OpenRouter, Resend, ...) stay blank here and
# need real secrets added via the Cloud Agent Secrets panel. Clerk runs in
# keyless dev mode automatically when no Clerk keys are present.
if [ ! -f .env ]; then
  cp .env.example .env
  sed -i \
    -e "s|^VOICE_PIPELINE=.*|VOICE_PIPELINE=vapi|" \
    -e "s|^DATABASE_URL=.*|DATABASE_URL=$LOCAL_DB_URL|" \
    -e "s|^DIRECT_URL=.*|DIRECT_URL=$LOCAL_DB_URL|" \
    -e "s|^NEXT_PUBLIC_APP_URL=.*|NEXT_PUBLIC_APP_URL=http://localhost:3000|" \
    .env
fi

# .env.local — minimal overrides; Next.js loads this with higher precedence.
if [ ! -f .env.local ]; then
  cat > .env.local <<EOF
# Local development env (gitignored). Generated by .cursor/install.sh.
VOICE_PIPELINE=vapi
DATABASE_URL=$LOCAL_DB_URL
DIRECT_URL=$LOCAL_DB_URL
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF
fi

echo "==> [5/6] Installing Node dependencies (postinstall runs prisma generate)"
npm ci

echo "==> [6/6] Syncing Prisma schema + pgvector index to the database"
set -a; . ./.env.local; set +a
npx prisma db push --skip-generate
npx prisma db execute --schema prisma/schema.prisma --file prisma/migrations/001_enable_pgvector.sql

echo "==> install.sh complete"
