export const ErrorCodes = {
  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  UNAUTHORIZED_DB: "UNAUTHORIZED",

  // Generic not found
  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  VARIABLE_NOT_FOUND: "VARIABLE_NOT_FOUND",
  ADDRESS_NOT_FOUND: "ADDRESS_NOT_FOUND",

  // Agent operations
  FAILED_TO_CREATE_AGENT: "FAILED_TO_CREATE_AGENT",
  FAILED_TO_FETCH_AGENTS: "FAILED_TO_FETCH_AGENTS",
  FAILED_TO_FETCH_AGENT: "FAILED_TO_FETCH_AGENT",
  FAILED_TO_UPDATE_AGENT: "FAILED_TO_UPDATE_AGENT",
  FAILED_TO_DUPLICATE_AGENT: "FAILED_TO_DUPLICATE_AGENT",
  FAILED_TO_DELETE_AGENT: "FAILED_TO_DELETE_AGENT",
  FAILED_TO_UPDATE_DEPLOYMENT: "FAILED_TO_UPDATE_DEPLOYMENT",

  // Deploy / integration
  UNKNOWN_DEPLOYMENT: "UNKNOWN_DEPLOYMENT",
  INTEGRATION_NOT_AVAILABLE: "INTEGRATION_NOT_AVAILABLE",

  // Chat widget
  FAILED_TO_UPDATE_CHAT_WIDGET: "FAILED_TO_UPDATE_CHAT_WIDGET",

  // Actions (suggested messages, leads, appointments, escalation, etc.)
  FAILED_TO_UPDATE_SUGGESTED_MESSAGES: "FAILED_TO_UPDATE_SUGGESTED_MESSAGES",
  FAILED_TO_UPDATE_COLLECT_LEADS: "FAILED_TO_UPDATE_COLLECT_LEADS",
  FAILED_TO_LOAD_LEADS: "FAILED_TO_LOAD_LEADS",
  FAILED_TO_UPDATE_BOOK_APPOINTMENT: "FAILED_TO_UPDATE_BOOK_APPOINTMENT",
  FAILED_TO_LOAD_APPOINTMENTS: "FAILED_TO_LOAD_APPOINTMENTS",
  FAILED_TO_UPDATE_ESCALATION: "FAILED_TO_UPDATE_ESCALATION",
  FAILED_TO_UPDATE_CUSTOM_BUTTON: "FAILED_TO_UPDATE_CUSTOM_BUTTON",
  FAILED_TO_UPDATE_CUSTOM_FORM: "FAILED_TO_UPDATE_CUSTOM_FORM",
  FAILED_TO_LOAD_FORM_SUBMISSIONS: "FAILED_TO_LOAD_FORM_SUBMISSIONS",
  FAILED_TO_UPDATE_HELP_PAGE: "FAILED_TO_UPDATE_HELP_PAGE",

  // Visibility / LLM / language / voice / prompt
  INVALID_VISIBILITY: "INVALID_VISIBILITY",
  FAILED_TO_UPDATE_VISIBILITY: "FAILED_TO_UPDATE_VISIBILITY",
  UNKNOWN_LLM_MODEL: "UNKNOWN_LLM_MODEL",
  FAILED_TO_UPDATE_LLM_SETTINGS: "FAILED_TO_UPDATE_LLM_SETTINGS",
  FAILED_TO_UPDATE_LANGUAGE_SETTINGS: "FAILED_TO_UPDATE_LANGUAGE_SETTINGS",
  FAILED_TO_UPDATE_VOICE_SETTINGS: "FAILED_TO_UPDATE_VOICE_SETTINGS",
  FAILED_TO_UPDATE_PROMPT_SETTINGS: "FAILED_TO_UPDATE_PROMPT_SETTINGS",
  FAILED_TO_LIST_VARIABLES: "FAILED_TO_LIST_VARIABLES",
  FAILED_TO_SAVE_VARIABLE: "FAILED_TO_SAVE_VARIABLE",
  FAILED_TO_DELETE_VARIABLE: "FAILED_TO_DELETE_VARIABLE",

  // Knowledge base
  FAILED_TO_FETCH_KNOWLEDGE_DOCS: "FAILED_TO_FETCH_KNOWLEDGE_DOCS",
  FAILED_TO_LOAD_AGENT_KNOWLEDGE: "FAILED_TO_LOAD_AGENT_KNOWLEDGE",
  FAILED_TO_ATTACH_DOCUMENT: "FAILED_TO_ATTACH_DOCUMENT",
  FAILED_TO_DETACH_DOCUMENT: "FAILED_TO_DETACH_DOCUMENT",
  FAILED_TO_LOAD_KNOWLEDGE_BASE: "FAILED_TO_LOAD_KNOWLEDGE_BASE",
  STORAGE_QUOTA_EXCEEDED: "STORAGE_QUOTA_EXCEEDED",
  TEXT_EXCEEDS_SIZE_LIMIT: "TEXT_EXCEEDS_SIZE_LIMIT",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  DELETE_FAILED: "DELETE_FAILED",
  FAILED_TO_FETCH_URL: "FAILED_TO_FETCH_URL",
  FAILED_TO_PARSE_SITEMAP: "FAILED_TO_PARSE_SITEMAP",
  NO_URLS_IN_SITEMAP: "NO_URLS_IN_SITEMAP",
  FAILED_TO_CRAWL_WEBSITE: "FAILED_TO_CRAWL_WEBSITE",
  NO_PAGES_ON_WEBSITE: "NO_PAGES_ON_WEBSITE",
  UNKNOWN_MODE: "UNKNOWN_MODE",
  COULD_NOT_CREATE_FOLDER: "COULD_NOT_CREATE_FOLDER",
  NO_FILES_SELECTED: "NO_FILES_SELECTED",
  INVALID_FOLDER: "INVALID_FOLDER",

  // API token
  FAILED_TO_ENSURE_API_TOKEN: "FAILED_TO_ENSURE_API_TOKEN",
  FAILED_TO_REGENERATE_API_TOKEN: "FAILED_TO_REGENERATE_API_TOKEN",

  // Sessions / inbox
  FAILED_TO_LOAD_DASHBOARD_STATS: "FAILED_TO_LOAD_DASHBOARD_STATS",
  FAILED_TO_LOAD_INBOX_SESSIONS: "FAILED_TO_LOAD_INBOX_SESSIONS",
  FAILED_TO_LOAD_CONVERSATION: "FAILED_TO_LOAD_CONVERSATION",
  FAILED_TO_LOAD_MESSAGES: "FAILED_TO_LOAD_MESSAGES",
  FAILED_TO_CLAIM_SESSION: "FAILED_TO_CLAIM_SESSION",
  FAILED_TO_UPDATE_SUMMARY: "FAILED_TO_UPDATE_SUMMARY",
  FAILED_TO_LOAD_AGENT_ANALYTICS: "FAILED_TO_LOAD_AGENT_ANALYTICS",
  FAILED_TO_SEND_MESSAGE: "FAILED_TO_SEND_MESSAGE",
  FAILED_TO_LOAD_LIVE_SESSIONS: "FAILED_TO_LOAD_LIVE_SESSIONS",
  ALREADY_CLAIMED: "ALREADY_CLAIMED",
  CANNOT_CLAIM_STATE: "CANNOT_CLAIM_STATE",
  CLAIM_BEFORE_REPLYING: "CLAIM_BEFORE_REPLYING",
  CANNOT_REPLY_STATE: "CANNOT_REPLY_STATE",

  // Phone
  FAILED_TO_LOAD_PHONE_SETTINGS: "FAILED_TO_LOAD_PHONE_SETTINGS",
  FAILED_TO_PROVISION_NUMBER: "FAILED_TO_PROVISION_NUMBER",
  FAILED_TO_DISCONNECT_NUMBER: "FAILED_TO_DISCONNECT_NUMBER",
  FAILED_TO_SAVE_PHONE_SETTINGS: "FAILED_TO_SAVE_PHONE_SETTINGS",
  PLAN_LIMIT_REACHED: "PLAN_LIMIT_REACHED",
  NUMBER_ALREADY_REGISTERED: "NUMBER_ALREADY_REGISTERED",
  INVALID_PHONE_NUMBER: "INVALID_PHONE_NUMBER",
  FAILED_TO_IMPORT_CARRIER: "FAILED_TO_IMPORT_CARRIER",
  TWILIO_NOT_CONFIGURED: "TWILIO_NOT_CONFIGURED",
  VAPI_IMPORT_FAILED: "VAPI_IMPORT_FAILED",

  // WhatsApp
  FAILED_TO_LOAD_WHATSAPP_SETTINGS: "FAILED_TO_LOAD_WHATSAPP_SETTINGS",
  FAILED_TO_SAVE_WHATSAPP_SETTINGS: "FAILED_TO_SAVE_WHATSAPP_SETTINGS",
  FAILED_TO_DISCONNECT_WHATSAPP: "FAILED_TO_DISCONNECT_WHATSAPP",

  // SMS
  FAILED_TO_LOAD_SMS_SETTINGS: "FAILED_TO_LOAD_SMS_SETTINGS",
  FAILED_TO_CONNECT_SMS: "FAILED_TO_CONNECT_SMS",
  FAILED_TO_DISCONNECT_SMS: "FAILED_TO_DISCONNECT_SMS",

  // Messenger
  FAILED_TO_LOAD_MESSENGER_SETTINGS: "FAILED_TO_LOAD_MESSENGER_SETTINGS",
  FAILED_TO_DISCONNECT_MESSENGER: "FAILED_TO_DISCONNECT_MESSENGER",

  // Gmail / email
  FAILED_TO_LOAD_GMAIL_SETTINGS: "FAILED_TO_LOAD_GMAIL_SETTINGS",
  FAILED_TO_DISCONNECT_GMAIL: "FAILED_TO_DISCONNECT_GMAIL",
  FAILED_TO_SAVE_GMAIL_SETTINGS: "FAILED_TO_SAVE_GMAIL_SETTINGS",
  FAILED_TO_SEND_TEST_EMAIL: "FAILED_TO_SEND_TEST_EMAIL",
  CONNECT_GMAIL_FIRST: "CONNECT_GMAIL_FIRST",
  FAILED_TO_LOAD_GMAIL_LABELS: "FAILED_TO_LOAD_GMAIL_LABELS",
  FAILED_TO_UPDATE_MAILBOX_WATCH: "FAILED_TO_UPDATE_MAILBOX_WATCH",

  // Inbound email addresses
  COULD_NOT_LOAD_EMAIL_INBOUND: "COULD_NOT_LOAD_EMAIL_INBOUND",
  AGENT_NOT_FOUND_IN_ORG: "AGENT_NOT_FOUND_IN_ORG",
  SELECT_ORG_FIRST: "SELECT_ORG_FIRST",
  ADDRESS_ALREADY_REGISTERED: "ADDRESS_ALREADY_REGISTERED",
  COULD_NOT_ADD_ADDRESS: "COULD_NOT_ADD_ADDRESS",
  COULD_NOT_UPDATE_SETTINGS: "COULD_NOT_UPDATE_SETTINGS",
  COULD_NOT_DELETE_ADDRESS: "COULD_NOT_DELETE_ADDRESS",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_REQUEST: "INVALID_REQUEST",

  // Validation
  INVALID_WEBSITE_URL: "INVALID_WEBSITE_URL",
  LINK_MUST_USE_HTTPS: "LINK_MUST_USE_HTTPS",
  LINK_MUST_BE_PATH_OR_URL: "LINK_MUST_BE_PATH_OR_URL",
  INVALID_KEY_FORMAT: "INVALID_KEY_FORMAT",
  INVALID_HEX_COLOR: "INVALID_HEX_COLOR",
  INVALID_FIELD_ID: "INVALID_FIELD_ID",
  SELECT_AT_LEAST_ONE_LANGUAGE: "SELECT_AT_LEAST_ONE_LANGUAGE",
  AGENT_NAME_REQUIRED: "AGENT_NAME_REQUIRED",
  NAME_TOO_LONG: "NAME_TOO_LONG",
  MAIN_GOAL_REQUIRED: "MAIN_GOAL_REQUIRED",
  MAIN_GOAL_TOO_LONG: "MAIN_GOAL_TOO_LONG",

  // Generic
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
